name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"
    - "version-[0-9]+.[0-9]+.[0-9]+"

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - run: git fetch --prune --unshallow
      - uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1.4.4
        with:
          java-version: 11
      - uses: actions/cache@f5ce41475b483ad7581884324a6eca9f48f8dcc7 # v1.2.1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Assemble release info
        id: release_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          . .github/workflows/release_info.sh ${{ github.event.repository.full_name }}
          echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
          echo ::set-output name=SKIP_RELEASE::${SKIP_RELEASE}
          echo ::set-output name=IS_CANDIDATE::${IS_CANDIDATE}
          echo ::set-output name=RELEASE_VERSION::${RELEASE_VERSION}
      - name: Release build
        env:
          ORG_GRADLE_PROJECT_version: ${{ steps.release_info.outputs.RELEASE_VERSION }}
          ORG_GRADLE_PROJECT_nexusPublishEnabled: true
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_nexusPgpSigningKey: ${{ secrets.NEXUS_PGP_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_nexusPgpSigningPassword: ${{ secrets.NEXUS_PGP_SIGNING_PASSWORD }}
        run: |
          ./gradlew --info publishToNexus closeAndReleaseNexusStagingRepository
      - name: Create release
        if: steps.release_info.outputs.SKIP_RELEASE == 'false'
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           tag_name: ${{ github.ref }}
           release_name: ${{ github.event.repository.name }} ${{ github.ref }}
           body: |
            ${{ steps.release_info.outputs.CHANGELOG }}
           draft: false
           prerelease: ${{ steps.release_info.outputs.IS_CANDIDATE }}
